Neos:
  MetaData:
    defaultEelContext:
      Array: 'Neos\Eel\Helper\ArrayHelper'

    metaDataMapping:
      title: '${asset.Title || iptc.Title || exif.ImageDescription}'
      caption: '${asset.Caption || iptc.Description}'
#      tags: '${asset.Tags}'
#      collections: '${asset.Collections}'
